name: messenger
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  camera: ^0.9.6
  cloud_firestore: ^3.1.15
  encrypt: ^5.0.1
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  firebase_remote_config: ^2.0.7
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
