name: secure_messenger
description: Secure Messenger
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: ^14.4.1
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  encrypt: ^5.0.1
  shared_preferences: ^2.1.0
  camera: ^0.10.5

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true